{{- if and .Values.adminToken.create (not .Values.adminToken.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "remote-jobs-api.adminSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "remote-jobs-api.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.adminToken.key }}: {{ randAlphaNum 40 | b64enc | quote }}
{{- end }}
